# Generated by Django 3.0.14 on 2024-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default=1, max_length=150, upload_to='Category/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
